workflow: added check to publish workflow for required secrets (PYPI_TOKEN)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -68,6 +68,12 @@ jobs:
       git-tags: ${{ steps.tags.outputs.git-tags }}
 
     steps:
+      - name: Fail without required secrets
+        if: ${{ ! secrets.PYPI_TOKEN }}
+        run: |
+          echo "::error::Secret undefined: PYPI_TOKEN"
+          exit 1
+
       - name: Check out repository
         uses: actions/checkout@v3
         with:
